services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
    networks:
      - appnet
    volumes:
      - .:/app

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - appnet

volumes:
  redis-data:

networks:
  appnet:
