"""logs Foreign key

Revision ID: 308ca45d59b9
Revises: b4cc7af8fbad
Create Date: 2025-07-24 16:11:23.939122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '308ca45d59b9'
down_revision = 'b4cc7af8fbad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('client_ip', sa.String(length=50), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.sk'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='logs'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_logs', schema='logs')
    # ### end Alembic commands ###
