"""Response Data

Revision ID: 7f9257af8603
Revises: 45a30adc1843
Create Date: 2025-07-25 14:28:35.375777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f9257af8603'
down_revision = '45a30adc1843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs',
        sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        schema='logs'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_logs', schema='logs')
    # ### end Alembic commands ###
